name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Hey :wave:, this issue has not received any input for a long while now, we would be closing this, for now, please feel free to re-open.'
        stale-pr-message: 'Hey :wave:, this PR has not received any input for a long while now, we would be closing this, for now, please feel free to re-open.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 60
        days-before-close: 5
